### ISSUE TITLE
Add support to siunitx v2

### ISSUE THREAD

**Issue by hellmrf** [gustaphe/UnitfulLatexify.jl#10]
The package was (gracefully!) updated to the new syntax available in Siunitx 3.0. However, I think it should be available, for backward compatibility, an option to use the v2 commands (`\SI`, `\si`, and so on), for users who are still using the older versions of the package (which is, basically, the huge majority of the people, including those who use `texlive` distributed by the distro's package manager, like `apt`).

I can try to implement that option, but I would need some guidance on how to do this (and on the design of this new thing).

**Comment by gustaphe** [comment]
You're right, that was a bit short-sighted. I just got excited by the new syntax. 

Does #11 make sense to you?
