### ISSUE TITLE
Temperature units not handled correctly

### ISSUE THREAD

**Issue by thomvet** [gustaphe/UnitfulLatexify.jl#6]
I noticed an issue with temperature units in this package. If I perform:
latexify(unit(1u"°C"))
The returned result is:
L"$\mathrm{K}$"
which of course can't be intentional within the context of this package :-)

**Comment by gustaphe** [comment]
That's a feature, keeps you from using affine units :p

This comes from the fact that `typeof(u"°C") == Unitful.FreeUnits{(K,), 𝚯, Unitful.Affine{-5463//20}}`, and also applies to `°F` and `Ra`. Going to need to do something clever about that.

**Comment by gustaphe** [comment]
Turns out Unitful.jl doesn't actually track the affine units, so I had to do something less clever and more ugly about it. But I think it should work with 68e3142.

**Comment by thomvet** [comment]
Just wanted to say thanks for fixing this so promptly. I tested the new version and it is working as intended! (and I agree that affine units have their challenges in general!)

**Comment by gustaphe** [comment]
Fixing bug reports is the only thing better than programming things nobody needs. Let me know if you encounter anything else :D
